//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksKaliteKontrolTakip.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POLY_QDMSEntities : DbContext
    {
        public POLY_QDMSEntities()
            : base("name=POLY_QDMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Qdms_Bolumler> Qdms_Bolumler { get; set; }
        public virtual DbSet<Qdms_Cari> Qdms_Cari { get; set; }
        public virtual DbSet<Qdms_Kullanici> Qdms_Kullanici { get; set; }
        public virtual DbSet<Qdms_MusteriSikayet> Qdms_MusteriSikayet { get; set; }
        public virtual DbSet<Qdms_MusteriSikayetAna> Qdms_MusteriSikayetAna { get; set; }
        public virtual DbSet<Qdms_MusteriSikayetResim> Qdms_MusteriSikayetResim { get; set; }
        public virtual DbSet<Qdms_PartiNo> Qdms_PartiNo { get; set; }
        public virtual DbSet<Qdms_SikayetGrubu> Qdms_SikayetGrubu { get; set; }
        public virtual DbSet<Qdms_SikayetSebebi> Qdms_SikayetSebebi { get; set; }
    }
}
