//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksKaliteKontrolTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qdms_Kullanici
    {
        public int ID { get; set; }
        public string KullaniciKodu { get; set; }
        public string PersonelKodu { get; set; }
        public string Birim { get; set; }
        public string Bolum { get; set; }
        public string AdSoyad { get; set; }
        public string Email { get; set; }
        public string Email2 { get; set; }
        public string Yetki { get; set; }
        public Nullable<int> Sifre { get; set; }
    }
}
