//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksKaliteKontrolTakip.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Qdms_MusteriSikayet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Qdms_MusteriSikayet()
        {
            this.Qdms_MusteriSikayetResim = new HashSet<Qdms_MusteriSikayetResim>();
        }
    
        public int ID { get; set; }
        public string IcDis { get; set; }
        public Nullable<System.DateTime> SikayetReklamasyonDuyuruTarihi { get; set; }
        public string PartiNo { get; set; }
        public string DtexFlaman { get; set; }
        public Nullable<decimal> KabulEdilenSikayetReklamasyonMiktari { get; set; }
        public string Kalite { get; set; }
        public string SikayetSonucu { get; set; }
        public Nullable<System.DateTime> NumuneGelisTarihi { get; set; }
        public Nullable<System.DateTime> CevapTarihi { get; set; }
        public Nullable<bool> TeknikZiyareti { get; set; }
        public string KapatilmaSuresi { get; set; }
        public string GecikmeNedeni { get; set; }
        public Nullable<decimal> IadeMiktari { get; set; }
        public Nullable<decimal> IadeBedeli { get; set; }
        public string IadeBedelBirimi { get; set; }
        public Nullable<decimal> IskontoBedeli { get; set; }
        public string IskontoBedeliBirimi { get; set; }
        public string MutabakatFormu { get; set; }
        public string KokNeden { get; set; }
        public string SonucOlarakYapilacakCalisma { get; set; }
        public string Sorumlu { get; set; }
        public Nullable<System.DateTime> AksiyonTermini { get; set; }
        public Nullable<System.DateTime> AksiyonGerceklestirmeTermini { get; set; }
        public string NumuneTipi { get; set; }
        public Nullable<int> Cari { get; set; }
        public Nullable<System.DateTime> SikayetReklamasyonGelisTarihi { get; set; }
        public Nullable<int> MusteriSikayetId { get; set; }
        public string IplikKullanimYeri { get; set; }
        public string FirmaYetkilisi { get; set; }
        public string SatisMusteriTemsilcisiAd { get; set; }
        public Nullable<System.DateTime> SatisMusteriTemsilcisiTarih { get; set; }
        public Nullable<int> Bobin { get; set; }
        public string Kumas { get; set; }
        public string Cile { get; set; }
        public string Diger { get; set; }
        public string DtexFlamanIplikOzeliigi { get; set; }
        public string SikayetIletisim { get; set; }
        public string Durum { get; set; }
        public Nullable<int> PartiNoSecme { get; set; }
        public Nullable<System.DateTime> SevkTarihi1 { get; set; }
        public Nullable<System.DateTime> SevkTarihi2 { get; set; }
        public Nullable<System.DateTime> SevkTarihi3 { get; set; }
        public Nullable<decimal> SevkMiktari1 { get; set; }
        public Nullable<decimal> SevkMiktari2 { get; set; }
        public Nullable<decimal> SevkMiktari3 { get; set; }
        public string SikayetDiger { get; set; }
        public Nullable<int> SikayetSebebiID { get; set; }
        public Nullable<int> SikayetGrubuID { get; set; }
        public string LabOzet { get; set; }
        [AllowHtml]
        public string YapilanAnalizler { get; set; }
        public string TekstureYorum { get; set; }
        public string BukumYorum { get; set; }
        public string UretimYorum { get; set; }
        public string TTYorum { get; set; }
        public string LabYorum { get; set; }
        public string PaketlemeYorum { get; set; }
        public string SevkiyatYorum { get; set; }
        public string SatinalmaYorum { get; set; }
        public string MBYorum { get; set; }
        public string EEYorum { get; set; }
        public string ProsesYorum { get; set; }
        public Nullable<bool> TekstureSeciliMi { get; set; }
        public Nullable<bool> UretimSeciliMi { get; set; }
        public Nullable<bool> BukumSeciliMi { get; set; }
        public Nullable<bool> TTSeciliMi { get; set; }
        public Nullable<bool> LabSeciliMi { get; set; }
        public Nullable<bool> PaketlemeSeciliMi { get; set; }
        public Nullable<bool> SevkiyatSeciliMi { get; set; }
        public Nullable<bool> SatinalmaSeciliMi { get; set; }
        public Nullable<bool> MBSeciliMi { get; set; }
        public Nullable<bool> EESeciliMi { get; set; }
        public Nullable<bool> ProsesSeciliMi { get; set; }
        public string Hazirlayan { get; set; }
        public string Onaylayan { get; set; }
        public string Kalite2 { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> OnaylandiMi { get; set; }
    
        public virtual Qdms_Cari Qdms_Cari { get; set; }
        public virtual Qdms_MusteriSikayetAna Qdms_MusteriSikayetAna { get; set; }
        public virtual Qdms_PartiNo Qdms_PartiNo { get; set; }
        public virtual Qdms_SikayetSebebi Qdms_SikayetSebebi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qdms_MusteriSikayetResim> Qdms_MusteriSikayetResim { get; set; }
    }
}
