//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksKaliteKontrolTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qdms_PartiNo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Qdms_PartiNo()
        {
            this.Qdms_MusteriSikayet = new HashSet<Qdms_MusteriSikayet>();
        }
    
        public int ID { get; set; }
        public string LotNo { get; set; }
        public string StokKodu { get; set; }
        public string StokAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Qdms_MusteriSikayet> Qdms_MusteriSikayet { get; set; }
    }
}
