//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolyteksKaliteKontrolTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOPLAM_SIKAYET
    {
        public int row_num { get; set; }
        public string SikayetGrubu { get; set; }
        public string SikayetSebebi { get; set; }
        public Nullable<int> TOPLAM { get; set; }
    }
}
